### ISSUE TITLE
volumio support

### ISSUE THREAD

**Issue by mecaz** [maddox/magic-cards#17]
Hello, 

How can we use this script with volumio?
Can i start playing spotify playlist with RFID cards on volumio. 

Regards.

**Comment by maddox** [comment]
If Volumio has an API, you can use the generic script actions. It allows you to run a shell script. Just use CURL in your shell script to make a request with the Volumio API.

https://github.com/maddox/magic-cards/blob/master/docs/actions.md#scripts
