### ISSUE TITLE
git clone auth fails

### ISSUE THREAD

**Issue by Velly56** [maddox/magic-cards#37]
Hi,
Trying step of cloning git:
git clone git@github.com:maddox/magic-cards.git

get following error:
![2019-07-25 19_51_13-Window](https://user-images.githubusercontent.com/47214541/61898421-f1fa3900-af21-11e9-877a-3983e7285162.jpg)

Thanks for help,
Vel

**Comment by maddox** [comment]
If you don't have an SSH key set up with GitHub, try using the HTTP clone url instead: https://github.com/maddox/magic-cards.git

**Comment by Velly56** [comment]
so I download full ZIP and then transfere by WinCP to pi/home?
Sorry for dumb enough question

**Comment by Velly56** [comment]
git clone https://github.com/maddox/magic-cards.git

right?

**Comment by maddox** [comment]
yep, do it like that.

**Comment by Velly56** [comment]
Everything working. Thanks for my card (long years ago) dream that you brought to life!

**Comment by maddox** [comment]
Awesome!! Have fun!
