### ISSUE TITLE
URI for spotify

### ISSUE THREAD

**Issue by DavidDeSloovere** [maddox/magic-cards#44]
What should the URI be for Spotify albums, tracks, playlists...?

I was guessing that it would be `spotify:album:1To7kv722A8SpZF789MZy7 `, but that's not working. It just calls `http://192.168.0.201:5005/Kitchen/spotify:album:1To7kv722A8SpZF789MZy7` which returns an error (in the JSON if you open this in browser, not in the logs)

After some investigating on the nodes sonos http api, I figured out that calling this works:
`http://192.168.0.201:5005/Kitchen/spotify/now/spotify:album:1To7kv722A8SpZF789MZy7`
Found at https://github.com/jishi/node-sonos-http-api#spotify-apple-music-and-amazon-music-experimental

So the URI value for the card would be: `spotify/now/spotify:album:1To7kv722A8SpZF789MZy7` 
So prefixing with **spotify/now/**.

Is that the correct way?

**Comment by derMick** [comment]
Hi David!

Spotify Albums are quite different to tracks. I read a little bit more about that topic. The album has to be queued to the Sonos playlist / queue. 

If you want to try the json commands to test your environment with Sonos and Spotify, start with songs :-) for playing albums you need more than one command.

Cheers
