### ISSUE TITLE
Not playing after using RFID card for playing Spotify album

### ISSUE THREAD

**Issue by derMick** [maddox/magic-cards#47]
Hello!
I have the docker installation, config for Sonos and Spotify working well. BUT the Sonos queue for a Spotify album is not automatically playing.

My docker logs are:
magic-cards       | [1] Read Card ID: 0123456789
magic-cards       | [1] Finding card...
magic-cards       | [1] Found card: Audio Book xyz. Processing...
magic-cards       | [1] Processing action: Sonos
magic-cards       | [1] Calling: http://127.0.0.1:5005/Kinderzimmer/repeat/all
magic-cards       | [1] Calling: http://127.0.0.1:5005/zones
magic-cards       | [1] Calling: http://127.0.0.1:5005/Kinderzimmer/SetAVTransportURI/x-rincon-queue:RINCON_000E58CAFF4E01400%230
magic-cards       | [1] Calling: http://127.0.0.1:5005/Kinderzimmer/clearqueue
magic-cards       | [1] Calling: http://127.0.0.1:5005/Kinderzimmer/shuffle/off
magic-cards       | [1] Calling: http://127.0.0.1:5005/Kinderzimmer/spotify/queue/spotify:album:5cJBmVANgdeXaHKreeOcGb

I changed rfid Id and album title, but you see the Spotify uri, and all is working well - instead of the final PLAY action of the Sonos queue. Is this Sonos command for Spotify albums missing?
Can anyone help me please? Thanks!

Regards derMick

And yes, the Sonos queue is filled correctly.

**Comment by derMick** [comment]
Is it possible, that the play method is missing between line 9 and 17 in file https://github.com/maddox/magic-cards/blob/master/scanner/actions/SonosAction.js ???

I can’t see and recognize any call of the play method. Can anyone test and give feedback please?

**Comment by rusteff** [comment]
I have the same problem, tried uppgrading to latest release but it still wont play.
It adds it to the que but does not start to play, if i open my Sonos app it's in the que and i can hitt play there.

2019-11-25T11:55:27.946626226Z [0] Found card: Xmas. Processing...
2019-11-25T11:55:27.946734508Z [0] Processing action: Sonos
2019-11-25T11:55:27.946772581Z [0] Calling: http://127.0.0.1:5005/Kitchen/repeat/all
2019-11-25T11:55:27.946830706Z [0] Calling: http://127.0.0.1:5005/zones
2019-11-25T11:55:27.946870810Z [0] Calling: http://127.0.0.1:5005/Kitchen/SetAVTransportURI/x-rincon-queue:RINCON_7828CAA8CCFC01400%230
2019-11-25T11:55:27.947243571Z [0] Calling: http://127.0.0.1:5005/Kitchen/clearqueue
2019-11-25T11:55:27.947275967Z [0] Calling: http://127.0.0.1:5005/Kitchen/shuffle/on
2019-11-25T11:55:27.947306800Z [0] Calling: http://127.0.0.1:5005/Kitchen/spotify/queue/spotify:playlist:6nP2FIKHcnoHkMtk22Lwr3
2019-11-25T11:55:27.947336956Z [0]   null

**Comment by derMick** [comment]
I think the auto play issues is placed as a pull request https://github.com/maddox/magic-cards/pull/43

**Comment by Delgnelm** [comment]
When you create your card, just change in the URI "queue" by "now" and it works fine.
Hence this: "/spotify/queue/spotify:playlist:6nP2FIKHcnoHkMtk22Lwr3" become this "/spotify/now/spotify:playlist:6nP2FIKHcnoHkMtk22Lwr3"

**Comment by derMick** [comment]
Great thanks for this advice!
