### ISSUE TITLE
Feature suggestion: Read barcodes

### ISSUE THREAD

**Issue by Joshfindit** [maddox/magic-cards#48]
While I've always loved the idea of RFID tags for media playback (can easily have a display shelf that guests can select from), there's possibly some benefit to *also* having the system read barcodes from a camera.

That way existing media could be used without it's own RFID tag.

![](https://4.bp.blogspot.com/-Ep1AuTHS5h0/VHwst9WvdZI/AAAAAAAAIak/S46r8COP35Q/s1600/LL%2BCool%2BJ%2B-%2BMama%2BSaid%2BKnock%2BYou%2BOut%2B-%2B(CD%2BSingle)%2B-%2B1991%2B-%2B(Back%2BScan%2BLR%2BWM)-djnastyboy.blogspot.com.jpg)

**Comment by maddox** [comment]
This isn't planned, but the addition of it would be welcomed if someone else did it.
